#!/usr/bin/env bash
set -euo pipefail

target_dir="$(pwd)"
include_all=0

usage() {
  cat <<'USAGE'
Usage: docs-index.sh [--target DIR] [--all]

Print a YAML index of DIR/docs Markdown notes built from their frontmatter, so an
agent can choose which docs to load without opening every file. The index is
generated on demand; do not store or edit it.

Options:
  --target DIR  Project directory to index. Defaults to current directory.
  --all         Include superseded and archived notes.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      if [[ $# -lt 2 ]]; then
        echo "missing value for --target" >&2
        exit 2
      fi
      target_dir="$2"
      shift 2
      ;;
    --all)
      include_all=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -d "$target_dir/docs" ]]; then
  echo "docs directory not found: $target_dir/docs" >&2
  exit 1
fi

cd "$target_dir"

# Parses one note. Emits "S<TAB>status", "C<TAB>glob<TAB>quoted warning" per
# code glob, and "Y<TAB>yaml line" for the index entry. Quoting lives here only.
awk_prog='
function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
function unquote(s,   f) {
  f = substr(s, 1, 1)
  if (length(s) >= 2 && (f == "\"" || f == sq) && substr(s, length(s), 1) == f) return substr(s, 2, length(s) - 2)
  return s
}
function q(s,   out, i, c) {
  out = ""
  for (i = 1; i <= length(s); i++) {
    c = substr(s, i, 1)
    if (c == "\\" || c == "\"") out = out "\\"
    out = out c
  }
  return "\"" out "\""
}
function add(key, val) {
  val = unquote(trim(val))
  if (val == "") return
  if (key == "type" || key == "status" || key == "summary") {
    if (!(key in scalar)) scalar[key] = val
    return
  }
  if (key != "aliases" && key != "related" && key != "code") return
  if (key == "related" && val ~ /^\[\[.*\]\]$/) {
    val = substr(val, 3, length(val) - 4)
    sub(/\|.*/, "", val)
    if (val !~ /\.[A-Za-z0-9]+$/) val = val ".md"
  }
  if (key == "code") codes[++ncode] = val
  list[key] = ((key in list) ? list[key] ", " : "") q(val)
}
BEGIN { sq = "\047" }
NR == 1 && $0 == "---" { fm = 1; next }
fm && $0 == "---" { fm = 0; next }
fm {
  if ($0 ~ /^[A-Za-z_][A-Za-z0-9_-]*:/) {
    cur = $0; sub(/:.*/, "", cur)
    val = $0; sub(/^[^:]*:/, "", val); val = trim(val)
    if (val ~ /^\[.*\]$/) {
      n = split(substr(val, 2, length(val) - 2), parts, ",")
      for (i = 1; i <= n; i++) add(cur, parts[i])
    } else {
      add(cur, val)
    }
  } else if ($0 ~ /^[ \t]+-/) {
    val = $0; sub(/^[ \t]+-/, "", val)
    add(cur, val)
  }
  next
}
/^```/ { fence = !fence; next }
!fence && title == "" && /^# / { title = trim(substr($0, 3)) }
END {
  status = ("status" in scalar) ? scalar["status"] : ""
  summary = ("summary" in scalar) ? scalar["summary"] : title
  if (summary == "") { summary = path; sub(/.*\//, "", summary); sub(/\.md$/, "", summary) }
  print "S\t" status
  for (i = 1; i <= ncode; i++) print "C\t" codes[i] "\t" q(path ": code glob matches no files: " codes[i])
  print "Y\t  - path: " q(path)
  if ("type" in scalar) print "Y\t    type: " q(scalar["type"])
  if (status != "") print "Y\t    status: " q(status)
  print "Y\t    summary: " q(summary)
  if ("aliases" in list) print "Y\t    aliases: [" list["aliases"] "]"
  if ("related" in list) print "Y\t    related: [" list["related"] "]"
  if ("code" in list) print "Y\t    code: [" list["code"] "]"
}
'

# A code glob is relative to the project root; ** is treated like * because
# find -path lets * match across directories.
glob_matches() {
  local pattern="./${1//\*\*/*}"
  local base="./${1%%[*?[]*}"
  base="${base%/*}"
  [[ -e "$base" ]] || return 1
  [[ -n "$(find "$base" -path "$pattern" -print 2>/dev/null | head -n 1)" ]]
}

entries=""
warnings=""
skipped=0

while IFS= read -r file; do
  status=""
  entry=""
  globs=""
  while IFS=$'\t' read -r kind value; do
    case "$kind" in
      S) status="$value" ;;
      C) globs+="$value"$'\n' ;;
      Y) entry+="$value"$'\n' ;;
    esac
  done < <(awk -v path="$file" "$awk_prog" "$file")

  if [[ "$include_all" -eq 0 && ( "$status" == superseded || "$status" == archived ) ]]; then
    skipped=$((skipped + 1))
    continue
  fi

  entries+="$entry"
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    glob_matches "${line%%$'\t'*}" || warnings+="  - ${line#*$'\t'}"$'\n'
  done <<< "$globs"
done < <(find docs -type f -name '*.md' -not -path 'docs/_templates/*' -not -path '*/.*' | LC_ALL=C sort)

printf '# Generated by Compass scripts/docs-index.sh from docs frontmatter. Do not store or edit.\n'
if [[ -n "$entries" ]]; then
  printf 'docs:\n%s' "$entries"
else
  printf 'docs: []\n'
fi
printf 'skipped: %d\n' "$skipped"
if [[ -n "$warnings" ]]; then
  printf 'warnings:\n%s' "$warnings"
fi
