#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/yaml.sh
source "$script_dir/lib/yaml.sh"

manifest="$script_dir/../references/recommended-skills.xml"
lock_file="$HOME/.agents/.skill-lock.json"
skill_dirs=""
target_dir="$(pwd)"

usage() {
  cat <<'USAGE'
Usage: skills-check.sh [--manifest FILE] [--lock FILE] [--skills-dir DIR]... [--target DIR]

Report which recommended skills are installed, without network access. Missing
skills come with an install command; run it only with developer approval.

Options:
  --manifest FILE   Recommended skills manifest. Defaults to the Compass manifest.
  --lock FILE       skills CLI lock file. Defaults to ~/.agents/.skill-lock.json.
  --skills-dir DIR  Folder that holds installed skills; repeatable. Defaults to the
                    shared and agent skill folders in the home directory and the
                    target project's .agents/skills and .claude/skills.
  --target DIR      Project directory; its docs/process/recommended-skills.xml adds
                    project skills. Defaults to the current directory.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest|--lock|--skills-dir|--target)
      if [[ $# -lt 2 ]]; then
        echo "missing value for $1" >&2
        exit 2
      fi
      case "$1" in
        --manifest) manifest="$2" ;;
        --lock) lock_file="$2" ;;
        --skills-dir) skill_dirs+="$2"$'\n' ;;
        --target) target_dir="$2" ;;
      esac
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$manifest" ]]; then
  echo "manifest not found: $manifest" >&2
  exit 1
fi

if [[ -z "$skill_dirs" ]]; then
  skill_dirs="$(printf '%s\n' "$HOME/.agents/skills" "$HOME/.claude/skills" "$HOME/.codex/skills" \
    "$HOME/.config/opencode/skills" "$HOME/.config/goose/skills" "$HOME/.config/crush/skills" \
    "$HOME/.cursor/skills" "$target_dir/.agents/skills" "$target_dir/.claude/skills")"
fi

# Prints "S<TAB>name<TAB>source<TAB>phase" for each skill element, or
# "I<TAB>message" for an entry without a name or source.
manifest_prog='
function attr(line, key,   start, rest) {
  start = index(line, " " key "=\"")
  if (!start) return ""
  rest = substr(line, start + length(key) + 3)
  return substr(rest, 1, index(rest, "\"") - 1)
}
/<skill[ >]/ {
  name = attr($0, "name"); source = attr($0, "source"); phase = attr($0, "phase")
  if (name == "") print "I\tinvalid skill entry in " label ": a skill has no name"
  else if (source == "") print "I\tinvalid skill entry in " label ": " name " has no source"
  else print "S\t" name "\t" source "\t" phase
}
'

entries="$(awk -v label="${manifest##*/}" "$manifest_prog" "$manifest")"
project_manifest="$target_dir/docs/process/recommended-skills.xml"
if [[ -f "$project_manifest" ]]; then
  entries+=$'\n'"$(awk -v label="docs/process/recommended-skills.xml" "$manifest_prog" "$project_manifest")"
fi

seen=$'\n'
skills_out=""
install_out=""
warnings_out=""
missing=0

while IFS=$'\t' read -r kind name source phase; do
  case "$kind" in
    I)
      warnings_out+="  - $(yaml_quote "$name")"$'\n'
      continue
      ;;
    S) ;;
    *) continue ;;
  esac

  # The first entry for a name wins, so core skills cannot be redefined.
  case "$seen" in
    *$'\n'"$name"$'\n'*) continue ;;
  esac
  seen+="$name"$'\n'

  status=missing
  while IFS= read -r dir; do
    if [[ -n "$dir" && -f "$dir/$name/SKILL.md" ]]; then
      status=installed
      break
    fi
  done < <(printf '%s\n' "$skill_dirs")

  managed=false
  if [[ -f "$lock_file" ]] && grep -Fq "\"$name\": {" "$lock_file"; then
    managed=true
  fi

  skills_out+="  - name: $(yaml_quote "$name")"$'\n'
  skills_out+="    source: $(yaml_quote "$source")"$'\n'
  [[ -z "$phase" ]] || skills_out+="    phase: $(yaml_quote "$phase")"$'\n'
  skills_out+="    status: \"$status\""$'\n'
  skills_out+="    managed: $managed"$'\n'

  if [[ "$status" == missing ]]; then
    missing=$((missing + 1))
    install_out+="  - $(yaml_quote "npx skills add $source --skill $name -g")"$'\n'
  fi
done < <(printf '%s\n' "$entries")

printf '# Generated by Compass scripts/skills-check.sh. Install a missing skill only with developer approval.\n'
if [[ -n "$skills_out" ]]; then
  printf 'skills:\n%s' "$skills_out"
else
  printf 'skills: []\n'
fi
printf 'missing: %d\n' "$missing"
if [[ -n "$install_out" ]]; then
  printf 'install:\n%s' "$install_out"
fi
if [[ -n "$warnings_out" ]]; then
  printf 'warnings:\n%s' "$warnings_out"
fi
